version: '3.8'

networks:
  codicodafr_network:
    driver: bridge
services:
  webserver:
    build: .
    ports:
      - "${HOST_PORT:-8080}:80"
    volumes:
      - ../:/var/www/codicoda.fr
    networks:
      - codicodafr_network
    restart: always
